### PR TITLE
Added JxBrowser 6.14.2 jars

### PR DESCRIPTION
**Pull request by psiinon**
Will submit a PR for the jxbrowser changes too :)

### CODE REVIEW

**Comment by thc202** [comment]
Worth removing oldest/older version(s)? (6.12, and 6.14?)

**Comment by psiinon** [comment]
I wasnt sure if we were leaving those so that people (inc us) could rebuild older versions easily?

**Comment by kingthorin** [comment]
I don't think they should need to. If there's an issue hopefully the Jx team fixes it quickly and we re-release. Failing that we can always roll back manually ourselves....

**Comment by thc202** [comment]
I think it's fine removing them, we can easily checkout a previous commit to use an older version, if needed.

**Comment by psiinon** [comment]
Ok, have removed them :)

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Pull request merged**
